variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.1"
  ANDROID_SDK_TOOLS:   "latest"
  COMMAND_LINE_TOOLS: "7583922"
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: release

stages:
  - build

dev:build:
  stage: build
  script:
    - sh -x build.sh
  tags:
    - android
