image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build
build-prod:
  stage: build
  only:
    - dev
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --token $APPCENTER_ACCESS_TOKEN
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with dev version of sdk'
      --app "Pointzi/FavDish-Prod-Bison-FavDish"
      --quiet
build-dev:
  stage: build
  only:
    - dev
  script:
    - ./gradlew assembleDebug
    - appcenter distribute release
      --token $APPCENTER_ACCESS_TOKEN
      --group Collaborators
      --file "app/build/outputs/apk/debug/app-debug.apk"
      --release-notes 'Bison server with dev version of sdk'
      --app "Pointzi/FavDish-Dev-Bison-FavDish"
      --quiet